### ISSUE TITLE
[BUG] CDK deployment fail in 'one-key-deploy'

### ISSUE THREAD

**Issue by Chris-wa-He** [aws-samples/stable-diffusion-on-eks#102]
**What happened**:

**To Reproduce**
1. Create EC2 with Amazon Linux 2023
2. Install Git, Python, npm with yum
3. Run deploy.sh

**Attach logs**
added 1 package in 2s
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
****************************************************
*** Newer version of CDK is available [2.132.1]  ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

Specify an environment name like 'aws://123456789012/us-east-1', or run in a directory with 'cdk.json'.

**What you expected to happen**: Deployment is completed without issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by yubingjiaocn** [comment]
The root cause is https://github.com/aws-samples/stable-diffusion-on-eks/blob/b91cbe5e53d016e8263c37bf335373bcc17661a2/deploy/install-tools.sh#L110

`cdk bootstrap` should run with project directory, not temp one. Fix in https://github.com/aws-samples/stable-diffusion-on-eks/blob/413b45ce541fbf87ce7863c2b115e3a52dd99bb6/deploy/deploy.sh#L54
