### ISSUE TITLE
[BUG]Error log found e in cloudwatch.

### ISSUE THREAD

**Issue by brilliantwf** [aws-samples/stable-diffusion-on-eks#96]
**What happened**:
Error log found  in cloudwatch log group

**To Reproduce**

check cloudwatch log group [/aws/eks/fluentbit-cloudwatch/logs]

    "time": "2024-03-06T22:34:57.661288073Z",
    "stream": "stderr",
    "_p": "F",
    "log": "mkdir: cannot create directory '/tmp/models/CLIP': Permission denied",
    "kubernetes": {
        "pod_name": "dynamicsdruntime-sd-on-eks-sd-webui-inference-api-56446477wlr7m",

{
    "time": "2024-03-06T22:35:04.442650075Z",
    "stream": "stdout",
    "_p": "F",
    "log": "Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled",

**Attach logs**
[log-events-viewer-result.csv](https://github.com/aws-samples/stable-diffusion-on-eks/files/14517789/log-events-viewer-result.csv)

**What you expected to happen**:

NO error log  and Expect to store workload logs in a separate log group such as: /aws/eks/fluentbit-cloudwatch/workload/default or /aws/eks/fluentbit-cloudwatch/workload/dynamic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
[v1.0.0-rc.1](https://github.com/aws-samples/stable-diffusion-on-eks/tree/v1.0.0-rc.1)

**Comment by yubingjiaocn** [comment]
For `"log": "Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled",`: 

It's an known issue in [v1.0.0-rc.1](https://github.com/aws-samples/stable-diffusion-on-eks/tree/v1.0.0-rc.1), which side-loaded NVIDIA Device Plugin and it has conflict with built-in NVDP with Bottlerocket OS. 

You can remove NVDP using `helm delete nvdp -n nvidia-device-plugin` as a workaround. 

This issue is already fixed in #91.
